# Коды профессиональных групп HH.ru
relevant_proles:
  - 10  # Аналитик
  - 25  # Гейм-дизайнер
  - 34  # Дизайнер, художник
  - 36  # Директор по информационным технологиям (CIO)
  - 73  # Менеджер продукта
  - 84  # Оператор ПК, оператор базы данных
  - 96  # Программист, разработчик
  - 104 # Руководитель группы разработки
  - 107 # Руководитель проектов
  - 112 # Сетевой инженер
  - 113 # Системный администратор
  - 114 # Системный инженер
  - 116 # Специалист по информационной безопасности
  - 121 # Специалист технической поддержки
  - 124 # Тестировщик
  - 125 # Технический директор (CTO)
  - 126 # Технический писатель
  - 148 # Системный аналитик
  - 150 # Бизнес-аналитик
  - 155 # Методолог
  - 156 # BI-аналитик, аналитик данных
  - 157 # Руководитель отдела аналитики
  - 160 # DevOps-инженер
  - 164 # Продуктовый аналитик
  - 165 # Дата-сайентист

# URL для получения вакансий
vacancies_url: https://api.hh.ru/vacancies